sc config WpcMonSvc start=demand
@REM sc start WpcMonSvc
sc config TroubleshootingSvc start=demand
@REM sc start TroubleshootingSvc
sc config SharedRealitySvc start=demand
@REM sc start SharedRealitySvc
sc config VacSvc start=demand
@REM sc start VacSvc
sc config RetailDemo start=demand
@REM sc start RetailDemo
sc config embeddedmode start=demand
@REM sc start embeddedmode
sc config dmwappushservice start=demand
@REM sc start dmwappushservice
sc config DmEnrollmentSvc start=demand
@REM sc start DmEnrollmentSvc
sc config autotimesvc start=demand
@REM sc start autotimesvc
sc config DusmSvc start=demand
@REM sc start DusmSvc
sc config OneSyncSvc_2322ed start=demand
@REM sc start OneSyncSvc_2322ed
sc config RmSvc start=demand
@REM sc start RmSvc
sc config DispBrokerDesktopSvc start=demand
@REM sc start DispBrokerDesktopSvc
sc config LxpSvc start=demand
@REM sc start LxpSvc
sc config tzautoupdate start=demand
@REM sc start tzautoupdate
sc config NaturalAuthentication start=demand
@REM sc start NaturalAuthentication
sc config SEMgrSvc start=demand
@REM sc start SEMgrSvc
sc config XblGameSave start=demand
@REM sc start XblGameSave
sc config XboxNetApiSvc start=demand
@REM sc start XboxNetApiSvc
sc config XblAuthManager start=demand
@REM sc start XblAuthManager
sc config XboxGipSvc start=demand
@REM sc start XboxGipSvc
sc config AxInstSV start=demand
@REM sc start AxInstSV
sc config AarSvc_2322ed start=demand 
@REM sc start AarSvc_2322ed
sc config AJRouter start=demand
@REM sc start AJRouter
sc config ALG start=demand
@REM sc start ALG
sc config AppMgmt start=demand
@REM sc start AppMgmt
sc config AppXSvc start=demand
@REM sc start AppXSvc
sc config AssignedAccessManagerSvc start=demand
@REM sc start AssignedAccessManagerSvc
sc config BthAvctpSvcstart=demand
@REM sc start BthAvctpSvcstart
sc config BITS start=demand
@REM sc start BITS
sc config PeerDistSvc start=demand
@REM sc start PeerDistSvc
sc config CaptureService_2322edc start=demand
@REM sc start CaptureService_2322edc
sc config CertPropSvc start=demand
@REM sc start CertPropSvc
sc config ClipSVC start=demand
@REM sc start ClipSVC
sc config DiagTrack start=demand
@REM sc start DiagTrack
sc config ConsentUxUserSvc_2322ed start=demand
@REM sc start ConsentUxUserSvc_2322ed
sc config PimIndexMaintenanceSvc_2322ed start=demand
@REM sc start PimIndexMaintenanceSvc_2322ed
sc config CredentialEnrollmentManagerUserSvc_2322ed start=demand
@REM sc start CredentialEnrollmentManagerUserSvc_2322ed
sc config CryptSvc start=demand
@REM sc start CryptSvc
sc config DsSvc start=demand
@REM sc start DsSvc
sc config Delivery Optimizationc start=demand
@REM sc start Delivery
sc config DeviceAssociationService start=demand
@REM sc start DeviceAssociationService
sc config DeviceAssociationBrokerSvc_2322ed start=demand
@REM sc start DeviceAssociationBrokerSvc_2322ed
sc config DevicePickerUserSvc_2322ed start=demand
@REM sc start DevicePickerUserSvc_2322ed
sc config DevicesFlowUserSvc_2322ed start=demand
@REM sc start DevicesFlowUserSvc_2322ed
sc config DevQueryBroker start=demand
@REM sc start DevQueryBroker
sc config Diagnostic Execution Service start=demand
@REM sc start Diagnostic
sc config DPS start=demand
@REM sc start DPS
sc config TrkWks start=demand
@REM sc start TrkWks
sc config MSDTC start=demand
@REM sc start MSDTC
sc config EFS start=demand
@REM sc start EFS
sc config EntAppSvc start=demand
@REM sc start EntAppSvc
sc config Eaphost start=demand
@REM sc start Eaphost
sc config FMAPOService start=demand
@REM sc start FMAPOService
sc config fdPHost start=demand
@REM sc start fdPHost
sc config FDResPub start=demand
@REM sc start FDResPub
sc config BcastDVRUserService_2322ed start=demand
@REM sc start BcastDVRUserService_2322ed
sc config lfsvc start=demand
@REM sc start lfsvc
sc config GraphicsPerfSvc start=demand
@REM sc start GraphicsPerfSvc
sc config HvHost start=demand
@REM sc start HvHost
sc config vmickvpexchange start=demand
@REM sc start vmickvpexchange
sc config vmicguestinterface start=demand
@REM sc start vmicguestinterface
sc config vmicshutdown start=demand
@REM sc start vmicshutdown
sc config vmicheartbeat start=demand
@REM sc start vmicheartbeat
sc config vmicvmsession start=demand
@REM sc start vmicvmsession
sc config vmictimesync start=demand
@REM sc start vmictimesync
sc config vmicvss start=demand
@REM sc start vmicvss
sc config vmicrdvstart=demand
@REM sc start vmicrdvstart
sc config ibtsiva start=demand
@REM sc start ibtsiva
sc config IntelAudioService start=demand
@REM sc start IntelAudioService
sc config cplspcon start=demand
@REM sc start cplspcon
sc config cphs start=demand
@REM sc start cphs
sc config SharedAccessstart=demand
@REM sc start SharedAccessstart
sc config iphlpsvc start=demand
@REM sc start iphlpsvc
sc config IpxlatCfgSvc start=demand
@REM sc start IpxlatCfgSvc
sc config MessagingService_2322ed start=demand
@REM sc start MessagingService_2322ed
sc config diagnosticshub.standardcollector.service start=demand
@REM sc start diagnosticshub
sc config wlidsvc start=demand
@REM sc start wlidsvc
sc config AppVClient start=demand
@REM sc start AppVClient
sc config MSiSCSI start=demand
@REM sc start MSiSCSI
sc config SmsRouter start=demand
@REM sc start SmsRouter
sc config Netlogon start=demand
@REM sc start Netlogon
sc config NcdAutoSetup start=demand
@REM sc start NcdAutoSetup
sc config Netman start=demand
@REM sc start Netman
sc config CscService start=demand
@REM sc start CscService
sc config PNRPsvc start=demand
@REM sc start PNRPsvc
sc config p2psvc start=demand
@REM sc start p2psvc
sc config p2pimsvc start=demand
@REM sc start p2pimsvc
sc config PhoneSvc start=demand
@REM sc start PhoneSvc
sc config PNRPAutoReg start=demand
@REM sc start PNRPAutoReg
sc config WPDBusEnum start=demand
@REM sc start WPDBusEnum
sc config Spooler start=demand
@REM sc start Spooler
sc config PrintNotify start=demand
@REM sc start PrintNotify
sc config PrintWorkflowUserSvc_2322ed start=demand
@REM sc start PrintWorkflowUserSvc_2322ed
sc config wercplsupport start=demand
@REM sc start wercplsupport
sc config PcaSvc start=demand
@REM sc start PcaSvc
sc config QWAVE start=demand
@REM sc start QWAVE
sc config RtkAudioUniversalService start=demand
@REM sc start RtkAudioUniversalService
sc config RasAuto start=demand
@REM sc start RasAuto
sc config RasMan start=demand
@REM sc start RasMan
sc config TermService start=demand
@REM sc start TermService
sc config UmRdpService start=demand
@REM sc start UmRdpService
sc config RemoteRegistry start=demand
@REM sc start RemoteRegistry
sc config RemoteAccess start=demand
@REM sc start RemoteAccess
sc config seclogon start=demand
@REM sc start seclogon
sc config SstpSvc start=demand
@REM sc start SstpSvc
sc config SensorDataService start=demand
@REM sc start SensorDataService
sc config SensrSvc start=demand
@REM sc start SensrSvc
sc config SensorService start=demand
@REM sc start SensorService
sc config LanmanServer start=demand
@REM sc start LanmanServer
sc config shpamsvc start=demand
@REM sc start shpamsvc
sc config ShellHWDetection start=demand
@REM sc start ShellHWDetection
sc config SCardSvr start=demand
@REM sc start SCardSvr
sc config ScDeviceEnum start=demand
@REM sc start ScDeviceEnum
sc config SCPolicySvc start=demand
@REM sc start SCPolicySvc
sc config SNMPTRAP start=demand
@REM sc start SNMPTRAP
sc config SSDPSRV start=demand
@REM sc start SSDPSRV
sc config StateRepository start=demand
@REM sc start StateRepository
sc config WiaRpc start=demand
@REM sc start WiaRpc
sc config TapiSrv start=demand
@REM sc start TapiSrv
sc config Themes start=demand
@REM sc start Themes
sc config UserDataSvc_2322ed start=demand
@REM sc start UserDataSvc_2322ed
sc config UnistoreSvc_2322ed start=demand
@REM sc start UnistoreSvc_2322ed
sc config UevAgentService start=demand
@REM sc start UevAgentService
sc config WalletService start=demand
@REM sc start WalletService
sc config WebClient start=demand
@REM sc start WebClient
sc config WarpJITSvc start=demand
@REM sc start WarpJITSvc
sc config TokenBroker start=demand
@REM sc start TokenBroker
sc config WbioSrvc start=demand
@REM sc start WbioSrvc
sc config FrameServer start=demand
@REM sc start FrameServer
sc config wcncsvc start=demand
@REM sc start wcncsvc
sc config  WEPHOSTSVC start=demand
@REM sc start WEPHOSTSVC
sc config WdNisSvc start=demand
@REM sc start WdNisSvc
sc config FontCache start=demand
@REM sc start FontCache
sc config Wecsvc start=demand
@REM sc start Wecsvc
sc config stisvc start=demand
@REM sc start stisvc
sc config WMPNetworkSvc start=demand
@REM sc start WMPNetworkSvc
sc config PushToInstall start=demand
@REM sc start PushToInstall
sc config WSearch start=demand
@REM sc start WSearch
sc config W32Time start=demand
@REM sc start W32Time
sc config spectrum start=demand
@REM sc start spectrum
sc config perceptionsimulation start=demand
@REM sc start perceptionsimulation
sc config WManSvc start=demand
@REM sc start WManSvc
sc config icssvc start=demand
@REM sc start icssvc
sc config wisvc start=demand
@REM sc start wisvc
sc config WinHttpAutoProxySvc start=demand
@REM sc start WinHttpAutoProxySvc
sc config dot3svc start=demand
@REM sc start dot3svc
sc config WFDSConMgrSvc start=demand
@REM sc start WFDSConMgrSvc
sc config workfolderssvc start=demand
@REM sc start workfolderssvc
sc config SysMain start=demand
@REM sc start SysMain
sc config GoogleChromeElevationService start=demand
@REM sc start GoogleChromeElevationService
sc config gupdate start=demand
@REM sc start gupdate
sc config gupdatem start=demand
@REM sc start gupdatem
sc config HpTouchpointAnalyticsService start=demand
@REM sc start HpTouchpointAnalyticsService
sc config HPAppHelperCap start=demand
@REM sc start HPAppHelperCap
sc config HPDiagsCap start=demand
@REM sc start HPDiagsCap
sc config HPNetworkCap start=demand
@REM sc start HPNetworkCap
sc config HPOmenCap start=demand
@REM sc start HPOmenCap
sc config HPSysInfoCap start=demand
@REM sc start HPSysInfoCap
sc config jhi_service start=demand
@REM sc start jhi_service
sc config igccservice start=demand
@REM sc start igccservice
sc config igfxCUIService2.0.0.0 start=demand
@REM sc start igfxCUIService2
sc config LMS start=demand
@REM sc start LMS
sc config iaStorAfsService start=demand
@REM sc start iaStorAfsService
sc config RstMwService start=demand
@REM sc start RstMwService
sc config MicrosoftEdgeElevationService start=demand
@REM sc start MicrosoftEdgeElevationService
sc config edgeupdate start=demand
@REM sc start edgeupdate
sc config edgeupdatem start=demand
@REM sc start edgeupdatem
sc config InstallService start=demand
@REM sc start InstallService