sc config WpcMonSvc start=disabled
@REM sc stop WpcMonSvc
sc config TroubleshootingSvc start=disabled
@REM sc stop TroubleshootingSvc
sc config SharedRealitySvc start=disabled
@REM sc stop SharedRealitySvc
sc config VacSvc start=disabled
@REM sc stop VacSvc
sc config RetailDemo start=disabled
@REM sc stop RetailDemo
sc config embeddedmode start=disabled
@REM sc stop embeddedmode
sc config dmwappushservice start=disabled
@REM sc stop dmwappushservice
sc config DmEnrollmentSvc start=disabled
@REM sc stop DmEnrollmentSvc
sc config autotimesvc start=disabled
@REM sc stop autotimesvc
sc config DusmSvc start=disabled
@REM sc stop DusmSvc
sc config OneSyncSvc_2322ed start=disabled
@REM sc stop OneSyncSvc_2322ed
sc config RmSvc start=disabled
@REM sc stop RmSvc
sc config DispBrokerDesktopSvc start=disabled
@REM sc stop DispBrokerDesktopSvc
sc config LxpSvc start=disabled
@REM sc stop LxpSvc
sc config tzautoupdate start=disabled
@REM sc stop tzautoupdate
sc config NaturalAuthentication start=disabled
@REM sc stop NaturalAuthentication
sc config SEMgrSvc start=disabled
@REM sc stop SEMgrSvc
sc config XblGameSave start=disabled
@REM sc stop XblGameSave
sc config XboxNetApiSvc start=disabled
@REM sc stop XboxNetApiSvc
sc config XblAuthManager start=disabled
@REM sc stop XblAuthManager
sc config XboxGipSvc start=disabled
@REM sc stop XboxGipSvc
sc config AxInstSV start=disabled
@REM sc stop AxInstSV
sc config AarSvc_2322ed start=disabled 
@REM sc stop AarSvc_2322ed
sc config AJRouter start=disabled
@REM sc stop AJRouter
sc config ALG start=disabled
@REM sc stop ALG
sc config AppMgmt start=disabled
@REM sc stop AppMgmt
sc config AppXSvc start=disabled
@REM sc stop AppXSvc
sc config AssignedAccessManagerSvc start=disabled
@REM sc stop AssignedAccessManagerSvc
sc config BthAvctpSvcstart=disabled
@REM sc stop BthAvctpSvcstart
sc config BITS start=disabled
@REM sc stop BITS
sc config PeerDistSvc start=disabled
@REM sc stop PeerDistSvc
sc config CaptureService_2322edc start=disabled
@REM sc stop CaptureService_2322edc
sc config CertPropSvc start=disabled
@REM sc stop CertPropSvc
sc config ClipSVC start=disabled
@REM sc stop ClipSVC
sc config DiagTrack start=disabled
@REM sc stop DiagTrack
sc config ConsentUxUserSvc_2322ed start=disabled
@REM sc stop ConsentUxUserSvc_2322ed
sc config PimIndexMaintenanceSvc_2322ed start=disabled
@REM sc stop PimIndexMaintenanceSvc_2322ed
sc config CredentialEnrollmentManagerUserSvc_2322ed start=disabled
@REM sc stop CredentialEnrollmentManagerUserSvc_2322ed
sc config CryptSvc start=disabled
@REM sc stop CryptSvc
sc config DsSvc start=disabled
@REM sc stop DsSvc
sc config Delivery Optimizationc start=disabled
@REM sc stop Delivery
sc config DeviceAssociationService start=disabled
@REM sc stop DeviceAssociationService
sc config DeviceAssociationBrokerSvc_2322ed start=disabled
@REM sc stop DeviceAssociationBrokerSvc_2322ed
sc config DevicePickerUserSvc_2322ed start=disabled
@REM sc stop DevicePickerUserSvc_2322ed
sc config DevicesFlowUserSvc_2322ed start=disabled
@REM sc stop DevicesFlowUserSvc_2322ed
sc config DevQueryBroker start=disabled
@REM sc stop DevQueryBroker
sc config Diagnostic Execution Service start=disabled
@REM sc stop Diagnostic
sc config DPS start=disabled
@REM sc stop DPS
sc config TrkWks start=disabled
@REM sc stop TrkWks
sc config MSDTC start=disabled
@REM sc stop MSDTC
sc config EFS start=disabled
@REM sc stop EFS
sc config EntAppSvc start=disabled
@REM sc stop EntAppSvc
sc config Eaphost start=disabled
@REM sc stop Eaphost
sc config FMAPOService start=disabled
@REM sc stop FMAPOService
sc config fdPHost start=disabled
@REM sc stop fdPHost
sc config FDResPub start=disabled
@REM sc stop FDResPub
sc config BcastDVRUserService_2322ed start=disabled
@REM sc stop BcastDVRUserService_2322ed
sc config lfsvc start=disabled
@REM sc stop lfsvc
sc config GraphicsPerfSvc start=disabled
@REM sc stop GraphicsPerfSvc
sc config HvHost start=disabled
@REM sc stop HvHost
sc config vmickvpexchange start=disabled
@REM sc stop vmickvpexchange
sc config vmicguestinterface start=disabled
@REM sc stop vmicguestinterface
sc config vmicshutdown start=disabled
@REM sc stop vmicshutdown
sc config vmicheartbeat start=disabled
@REM sc stop vmicheartbeat
sc config vmicvmsession start=disabled
@REM sc stop vmicvmsession
sc config vmictimesync start=disabled
@REM sc stop vmictimesync
sc config vmicvss start=disabled
@REM sc stop vmicvss
sc config vmicrdvstart=disabled
@REM sc stop vmicrdvstart
sc config ibtsiva start=disabled
@REM sc stop ibtsiva
sc config IntelAudioService start=disabled
@REM sc stop IntelAudioService
sc config cplspcon start=disabled
@REM sc stop cplspcon
sc config cphs start=disabled
@REM sc stop cphs
sc config SharedAccessstart=disabled
@REM sc stop SharedAccessstart
sc config iphlpsvc start=disabled
@REM sc stop iphlpsvc
sc config IpxlatCfgSvc start=disabled
@REM sc stop IpxlatCfgSvc
sc config MessagingService_2322ed start=disabled
@REM sc stop MessagingService_2322ed
sc config diagnosticshub.standardcollector.service start=disabled
@REM sc stop diagnosticshub
sc config wlidsvc start=disabled
@REM sc stop wlidsvc
sc config AppVClient start=disabled
@REM sc stop AppVClient
sc config MSiSCSI start=disabled
@REM sc stop MSiSCSI
sc config SmsRouter start=disabled
@REM sc stop SmsRouter
sc config Netlogon start=disabled
@REM sc stop Netlogon
sc config NcdAutoSetup start=disabled
@REM sc stop NcdAutoSetup
sc config Netman start=disabled
@REM sc stop Netman
sc config CscService start=disabled
@REM sc stop CscService
sc config PNRPsvc start=disabled
@REM sc stop PNRPsvc
sc config p2psvc start=disabled
@REM sc stop p2psvc
sc config p2pimsvc start=disabled
@REM sc stop p2pimsvc
sc config PhoneSvc start=disabled
@REM sc stop PhoneSvc
sc config PNRPAutoReg start=disabled
@REM sc stop PNRPAutoReg
sc config WPDBusEnum start=disabled
@REM sc stop WPDBusEnum
sc config Spooler start=disabled
@REM sc stop Spooler
sc config PrintNotify start=disabled
@REM sc stop PrintNotify
sc config PrintWorkflowUserSvc_2322ed start=disabled
@REM sc stop PrintWorkflowUserSvc_2322ed
sc config wercplsupport start=disabled
@REM sc stop wercplsupport
sc config PcaSvc start=disabled
@REM sc stop PcaSvc
sc config QWAVE start=disabled
@REM sc stop QWAVE
sc config RtkAudioUniversalService start=disabled
@REM sc stop RtkAudioUniversalService
sc config RasAuto start=disabled
@REM sc stop RasAuto
sc config RasMan start=disabled
@REM sc stop RasMan
sc config TermService start=disabled
@REM sc stop TermService
sc config UmRdpService start=disabled
@REM sc stop UmRdpService
sc config RemoteRegistry start=disabled
@REM sc stop RemoteRegistry
sc config RemoteAccess start=disabled
@REM sc stop RemoteAccess
sc config seclogon start=disabled
@REM sc stop seclogon
sc config SstpSvc start=disabled
@REM sc stop SstpSvc
sc config SensorDataService start=disabled
@REM sc stop SensorDataService
sc config SensrSvc start=disabled
@REM sc stop SensrSvc
sc config SensorService start=disabled
@REM sc stop SensorService
sc config LanmanServer start=disabled
@REM sc stop LanmanServer
sc config shpamsvc start=disabled
@REM sc stop shpamsvc
sc config ShellHWDetection start=disabled
@REM sc stop ShellHWDetection
sc config SCardSvr start=disabled
@REM sc stop SCardSvr
sc config ScDeviceEnum start=disabled
@REM sc stop ScDeviceEnum
sc config SCPolicySvc start=disabled
@REM sc stop SCPolicySvc
sc config SNMPTRAP start=disabled
@REM sc stop SNMPTRAP
sc config SSDPSRV start=disabled
@REM sc stop SSDPSRV
sc config StateRepository start=disabled
@REM sc stop StateRepository
sc config WiaRpc start=disabled
@REM sc stop WiaRpc
sc config TapiSrv start=disabled
@REM sc stop TapiSrv
sc config Themes start=disabled
@REM sc stop Themes
sc config UserDataSvc_2322ed start=disabled
@REM sc stop UserDataSvc_2322ed
sc config UnistoreSvc_2322ed start=disabled
@REM sc stop UnistoreSvc_2322ed
sc config UevAgentService start=disabled
@REM sc stop UevAgentService
sc config WalletService start=disabled
@REM sc stop WalletService
sc config WebClient start=disabled
@REM sc stop WebClient
sc config WarpJITSvc start=disabled
@REM sc stop WarpJITSvc
sc config TokenBroker start=disabled
@REM sc stop TokenBroker
sc config WbioSrvc start=disabled
@REM sc stop WbioSrvc
sc config FrameServer start=disabled
@REM sc stop FrameServer
sc config wcncsvc start=disabled
@REM sc stop wcncsvc
sc config  WEPHOSTSVC start=disabled
@REM sc stop WEPHOSTSVC
sc config WdNisSvc start=disabled
@REM sc stop WdNisSvc
sc config FontCache start=disabled
@REM sc stop FontCache
sc config Wecsvc start=disabled
@REM sc stop Wecsvc
sc config stisvc start=disabled
@REM sc stop stisvc
sc config WMPNetworkSvc start=disabled
@REM sc stop WMPNetworkSvc
sc config PushToInstall start=disabled
@REM sc stop PushToInstall
sc config WSearch start=disabled
@REM sc stop WSearch
sc config W32Time start=disabled
@REM sc stop W32Time
sc config spectrum start=disabled
@REM sc stop spectrum
sc config perceptionsimulation start=disabled
@REM sc stop perceptionsimulation
sc config WManSvc start=disabled
@REM sc stop WManSvc
sc config wisvc start=disabled
@REM sc stop wisvc
sc config WinHttpAutoProxySvc start=disabled
@REM sc stop WinHttpAutoProxySvc
sc config dot3svc start=disabled
@REM sc stop dot3svc
sc config WFDSConMgrSvc start=disabled
@REM sc stop WFDSConMgrSvc
sc config workfolderssvc start=disabled
@REM sc stop workfolderssvc
sc config SysMain start=disabled
@REM sc stop SysMain
sc config GoogleChromeElevationService start=disabled
@REM sc stop GoogleChromeElevationService
sc config gupdate start=disabled
@REM sc stop gupdate
sc config gupdatem start=disabled
@REM sc stop gupdatem
sc config HpTouchpointAnalyticsService start=disabled
@REM sc stop HpTouchpointAnalyticsService
sc config HPAppHelperCap start=disabled
@REM sc stop HPAppHelperCap
sc config HPDiagsCap start=disabled
@REM sc stop HPDiagsCap
sc config HPNetworkCap start=disabled
@REM sc stop HPNetworkCap
sc config HPOmenCap start=disabled
@REM sc stop HPOmenCap
sc config HPSysInfoCap start=disabled
@REM sc stop HPSysInfoCap
sc config jhi_service start=disabled
@REM sc stop jhi_service
sc config igccservice start=disabled
@REM sc stop igccservice
sc config igfxCUIService2.0.0.0 start=disabled
@REM sc stop igfxCUIService2
sc config LMS start=disabled
@REM sc stop LMS
sc config iaStorAfsService start=disabled
@REM sc stop iaStorAfsService
sc config RstMwService start=disabled
@REM sc stop RstMwService
sc config MicrosoftEdgeElevationService start=disabled
@REM sc stop MicrosoftEdgeElevationService
sc config edgeupdate start=disabled
@REM sc stop edgeupdate
sc config edgeupdatem start=disabled
@REM sc stop edgeupdatem
sc config InstallService start=disabled
@REM sc stop InstallService